### ISSUE TITLE
anidb刮削的全是英文，有版本切换中文源么>

### ISSUE THREAD

**Issue by ltlt4** [Pockies/pockies.github.io#54]
> 
> 
> > > > > > > > > @q7091696665 @swat00789
> > > > > > > > > 大佬，终于我也跟着你搭建起来了~但是这两天很纠结一个问题。。。。里番怎么都刮削不好，TMDB有信息，但是TMM搜索不到.....大佬有什么好方法吗
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 里番只能用EverAver一部一部手动刮。
> > > > > > > 
> > > > > > > 
> > > > > > > 里番可以anidb 但是我用的emby 不知道jellyfin有没有
> > > > > > 
> > > > > > 
> > > > > > 能具体说说吗，里番毕竟没有季，难道还要S01？
> > > > > 
> > > > > 
> > > > > 没啥说的啊 直接把其他参数去掉只留名字就行了
> > > > 
> > > > 
> > > > 试过了，aindb不认，不管是日语还是英语。anidb也注册了设置里显示成人内容
> > > 
> > > 
> > > 不知道你怎么回事 我的好好的 建议自己多试试
> > > 比如Ajisai no Chiru Koro ni (a15780)，我直接 Ajisai no Chiru Koro ni  搜不到。。。
> 
> ![image](https://user-images.githubusercontent.com/38862056/105153096-fcab8380-5b42-11eb-95b4-52257dd7ad90.png)
> 然后就自动识别了
我是多层目录，应该不影响吧，比如，目录：Adult Anime——Ajisai no Chiru Koro ni——Ajisai no Chiru Koro ni（视频）

_Originally posted by @swat00789 in https://github.com/Pockies/pockies.github.io/issues/45#issuecomment-763460483_

**Comment by nwq115212** [comment]
+1 我也是里番刮不到
